// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller.js"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import FlipCardsController from "./flip_cards_controller.js"
application.register("flip-cards", FlipCardsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import StarRatingController from "./star_rating_controller.js"
application.register("star-rating", StarRatingController)

import TypedJsController from "./typed_js_controller.js"
application.register("typed-js", TypedJsController)
